package com.automanage.system.dao.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TSysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.ID
     *
     * @mbg.generated
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.CODE
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.REGION_ID
     *
     * @mbg.generated
     */
    private BigDecimal regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.DUTY_ID
     *
     * @mbg.generated
     */
    private BigDecimal dutyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.LOGIN_NUM
     *
     * @mbg.generated
     */
    private BigDecimal loginNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.DEPARTMENT_ID
     *
     * @mbg.generated
     */
    private BigDecimal departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.CREATOR_ID
     *
     * @mbg.generated
     */
    private BigDecimal creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.MODIFIER_ID
     *
     * @mbg.generated
     */
    private BigDecimal modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.MODIFY_DATE
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.VERSION
     *
     * @mbg.generated
     */
    private BigDecimal version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.CONTACT_TELEPHONE
     *
     * @mbg.generated
     */
    private String contactTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.ID
     *
     * @return the value of t_sys_user.ID
     *
     * @mbg.generated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.ID
     *
     * @param id the value for t_sys_user.ID
     *
     * @mbg.generated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.CODE
     *
     * @return the value of t_sys_user.CODE
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.CODE
     *
     * @param code the value for t_sys_user.CODE
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.NAME
     *
     * @return the value of t_sys_user.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.NAME
     *
     * @param name the value for t_sys_user.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.PASSWORD
     *
     * @return the value of t_sys_user.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.PASSWORD
     *
     * @param password the value for t_sys_user.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.REGION_ID
     *
     * @return the value of t_sys_user.REGION_ID
     *
     * @mbg.generated
     */
    public BigDecimal getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.REGION_ID
     *
     * @param regionId the value for t_sys_user.REGION_ID
     *
     * @mbg.generated
     */
    public void setRegionId(BigDecimal regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.DUTY_ID
     *
     * @return the value of t_sys_user.DUTY_ID
     *
     * @mbg.generated
     */
    public BigDecimal getDutyId() {
        return dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.DUTY_ID
     *
     * @param dutyId the value for t_sys_user.DUTY_ID
     *
     * @mbg.generated
     */
    public void setDutyId(BigDecimal dutyId) {
        this.dutyId = dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.LOGIN_NUM
     *
     * @return the value of t_sys_user.LOGIN_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getLoginNum() {
        return loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.LOGIN_NUM
     *
     * @param loginNum the value for t_sys_user.LOGIN_NUM
     *
     * @mbg.generated
     */
    public void setLoginNum(BigDecimal loginNum) {
        this.loginNum = loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.DEPARTMENT_ID
     *
     * @return the value of t_sys_user.DEPARTMENT_ID
     *
     * @mbg.generated
     */
    public BigDecimal getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.DEPARTMENT_ID
     *
     * @param departmentId the value for t_sys_user.DEPARTMENT_ID
     *
     * @mbg.generated
     */
    public void setDepartmentId(BigDecimal departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.DESCRIPTION
     *
     * @return the value of t_sys_user.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.DESCRIPTION
     *
     * @param description the value for t_sys_user.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.CREATOR_ID
     *
     * @return the value of t_sys_user.CREATOR_ID
     *
     * @mbg.generated
     */
    public BigDecimal getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.CREATOR_ID
     *
     * @param creatorId the value for t_sys_user.CREATOR_ID
     *
     * @mbg.generated
     */
    public void setCreatorId(BigDecimal creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.CREATE_DATE
     *
     * @return the value of t_sys_user.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.CREATE_DATE
     *
     * @param createDate the value for t_sys_user.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.MODIFIER_ID
     *
     * @return the value of t_sys_user.MODIFIER_ID
     *
     * @mbg.generated
     */
    public BigDecimal getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.MODIFIER_ID
     *
     * @param modifierId the value for t_sys_user.MODIFIER_ID
     *
     * @mbg.generated
     */
    public void setModifierId(BigDecimal modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.MODIFY_DATE
     *
     * @return the value of t_sys_user.MODIFY_DATE
     *
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.MODIFY_DATE
     *
     * @param modifyDate the value for t_sys_user.MODIFY_DATE
     *
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.VERSION
     *
     * @return the value of t_sys_user.VERSION
     *
     * @mbg.generated
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.VERSION
     *
     * @param version the value for t_sys_user.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.CONTACT_TELEPHONE
     *
     * @return the value of t_sys_user.CONTACT_TELEPHONE
     *
     * @mbg.generated
     */
    public String getContactTelephone() {
        return contactTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.CONTACT_TELEPHONE
     *
     * @param contactTelephone the value for t_sys_user.CONTACT_TELEPHONE
     *
     * @mbg.generated
     */
    public void setContactTelephone(String contactTelephone) {
        this.contactTelephone = contactTelephone == null ? null : contactTelephone.trim();
    }
}